### ISSUE TITLE
Thread leak when close connection

### ISSUE THREAD

**Issue by lionelfer** [shinyhut/vernacular-vnc#9]
Hi @shinyhut,
I use version 1.9, and found that one thread is remaining after a disconnection.
It is visible with the VernacularViewer or with the API. 
To be more precise, on disconnection, one thread stays blocked in VernacularClient.stop() method.
I tried to make clientEventHandler.stop() before serverEventHandler.stop() and it solved the problem. 
I don't know if this modification is the good one, but hope it will help somehow.

**Comment by shinyhut** [comment]
Thanks @lionelfer. I believe the thread is actually blocked in `VncSession.waitForFramebufferUpdate()` - this will have been introduced by our fix for https://github.com/shinyhut/vernacular-vnc/issues/5 where we changed the client so it waits for a framebuffer update from the server before it requests another one. In this case, the update never comes because we've already terminated the thread that's listening for them. As you say, stopping the `ClientEventHandler` before the `ServerEventHandler` would reduce the issue, but it's not perfect because we would still wait indefinitely in cases where the server legitimately doesn't have an update for us. Instead, I've modified `ClientEventHandler.stop()` so it explicitly interrupts the thread that's blocked awaiting framebuffer updates.

Do you want to try this branch: [bugfix/9-thread-leak-on-disconnect](https://github.com/shinyhut/vernacular-vnc/tree/bugfix/9-thread-leak-on-disconnect), and see if it resolves the issue for you?

**Comment by lionelfer** [comment]
Yes, I will try your fix in about a day.

**Comment by lionelfer** [comment]
I tried your bugfix and it works well.
Thanks very much for your reactivity and clarity in your explanation.

**Comment by shinyhut** [comment]
Ok, that's been merged and released as [v1.10.0](https://github.com/shinyhut/vernacular-vnc/releases/tag/v1.10.0)
